name: flutter_secure_storage_macos
description: macOS implementation of flutter_secure_storage
repository: https://github.com/mogol/flutter_secure_storage
version: 3.0.1

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git:
      url: https://github.com/mansourzaki/flutter_secure_storage
      ref: develop
      path: flutter_secure_storage_platform_interface

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      macos:
        pluginClass: FlutterSecureStoragePlugin
